version: '3'
services:
  redis:
    image: redis:alpine
    volumes:
      - ./redis_data:/data

  bot:
    build: .
    command: python main.py
    env_file:
      - .env
    depends_on:
      - redis